# Generated by Django 2.1.7 on 2019-02-12 11:12

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("good", "good"),
                            ("flagged", "flagged"),
                            ("hidden", "hidden"),
                        ],
                        default="good",
                        max_length=10,
                        verbose_name="moderation status",
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(verbose_name="text")),
                (
                    "authored_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="authored by",
                    ),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "post",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("annoying", "It's annoying or not interesting"),
                            ("misplaced", "I think it shouldn't be here"),
                            ("spam", "It's spam"),
                        ],
                        max_length=10,
                        verbose_name="reason",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Anything else you want to say?",
                        verbose_name="notes",
                    ),
                ),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="handled at"
                    ),
                ),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("good", "good"),
                            ("flagged", "flagged"),
                            ("hidden", "hidden"),
                        ],
                        default="flagged",
                        max_length=10,
                        verbose_name="moderation status",
                    ),
                ),
                (
                    "authored_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="authored by",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="handled by",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="tinyforum.Post",
                        verbose_name="post",
                    ),
                ),
            ],
            options={
                "verbose_name": "post report",
                "verbose_name_plural": "post reports",
            },
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("good", "good"),
                            ("flagged", "flagged"),
                            ("hidden", "hidden"),
                        ],
                        default="good",
                        max_length=10,
                        verbose_name="moderation status",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Pinned threads are shown at the top of the thread list.",
                        verbose_name="is pinned",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="closed at"
                    ),
                ),
                (
                    "post_count",
                    models.IntegerField(default=0, verbose_name="post count"),
                ),
                (
                    "authored_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="authored by",
                    ),
                ),
                (
                    "latest_post",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tinyforum.Post",
                        verbose_name="latest post",
                    ),
                ),
                (
                    "starred_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="starred_threads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="starred by",
                    ),
                ),
            ],
            options={
                "verbose_name": "thread",
                "verbose_name_plural": "threads",
                "ordering": ["-is_pinned", "-latest_post__created_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="tinyforum.Thread",
                verbose_name="thread",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postreport", unique_together={("authored_by", "post")}
        ),
    ]
